---
- name: Create ServiceNow Change Request
  servicenow.itsm.change_request_info:
    instance: 
      host: "https://{{ lookup('env', 'SN_INSTANCE') }}.service-now.com/"
    type: normal
    short_description: "{{ cr_description }}"
    priority: high
    risk: moderate
    impact: low
    assignment_group: "CAB Approval"
  register: request
  delegate_to: localhost

- name: Pass along request information
  ansible.builtin.set_stats:
    data:
      request: "{{ request }}"
    per_host: no
  delegate_to: localhost

- name: Send Approval e-mail
  community.general.mail:
    host: "{{ EMAIL_HOST }}"
    username: "{{ EMAIL_USERNAME }}"
    password: "{{ EMAIL_PASSWORD }}"
    port: "{{ EMAIL_PORT }}"
    subject: "Approval request for ServiceNow Change Request {{ request.record.number }}"
    body: "You have a new CR Approval request. Please click on this URL to approve: https://{{ lookup('env', 'SN_INSTANCE') }}.service-now.com/nav_to.do?uri=change_request.do?sysparm_query=number={{ request.record.number }}"
    from: tower@shadowman.dev
    to: "{{ to_email }}"
  delegate_to: localhost  

- name: Wait for Change Request approval
  servicenow.itsm.change_request_info:
    number: "{{ request.record.number }}"
    instance: 
      host: "https://{{ lookup('env', 'SN_INSTANCE') }}.service-now.com/"
  until: change_request_status.records[0].state == "scheduled"
  retries: 50
  delay: 10
  register: change_request_status
  delegate_to: localhost

- name: Update to implement the change request in ServiceNow
  servicenow.itsm.change_request:
    state: implement
    instance: 
      host: "https://{{ lookup('env', 'SN_INSTANCE') }}.service-now.com/"
    number: "{{ request.record.number }}"
    assignment_group: "CAB Approval"
  delegate_to: localhost