---
- name: Create ServiceNow User
  servicenow.itsm.api:
    resource: sys_user
    query_params:
      sysparm_input_display_value: true
    action: post
    data:
      user_name: "{{ snow_username }}"
      user_password: "{{ snow_password }}"
      first_name: "{{ first_name }}"
      last_name: "{{ last_name }}"
      department: IT
      email: "{{ snow_username }}@shadowman.dev"
      title: Shadowman
  register: user

- name: Attach role to new user
  servicenow.itsm.api:
    action: post
    resource: sys_user_has_role
    data:
      user: "{{ snow_username }}"
      role: admin
