---
- name: Create ticket
  ansible.builtin.include_tasks: servicenow_create.yml
  when: servicenow_ticket == "create"

- name: Update ticket
  ansible.builtin.include_tasks: servicenow_update.yml
  when: servicenow_ticket == "update"

- name: Close ticket
  ansible.builtin.include_tasks: servicenow_close.yml
  when: servicenow_ticket == "close"

- name: Find ticket information
  ansible.builtin.include_tasks: servicenow_find.yml
  when: servicenow_ticket == "find"
