- name: Create an incident in ServiceNow for IP Blocking
  hosts: localhost
  gather_facts: false
  connection: local

  vars:
    short_description: "Ansible Tower IP Block"
    urgency: high
    impact: high
    servicenow_ticket: "create"
 
  roles:
    - servicenow_create