- name: Create an incident in ServiceNow for IP Blocking
  hosts: localhost
  gather_facts: false
  connection: local

  collections:
    - servicenow.servicenow
  
  tasks: 
  
  - name: Create an incident in ServiceNow
    servicenow.servicenow.snow_record:
      state: present
      data:
        short_description: "Ansible Tower IP Block"
        caller_id: "System Administrator"
        urgency: "1 - High"
        impact: "1 - High"
        u_ip_address: "{{ ip_addr }}"
    register: new_incident

  - debug: 
      var: new_incident.record.number