- name: Update an incident in ServiceNow
  hosts: all
  gather_facts: false
  connection: local

  collections:
    - servicenow.itsm
  
  tasks: 
  
  - name: Update an incident in ServiceNow
    servicenow.itsm.incident:
      state: in_progress
      number: "{{ ticket_number }}"
      other:
        comments: "{{ comment }}"
    delegate_to: localhost