- name: Close a change request
  hosts: localhost
  gather_facts: false
  connection: local

  collections:
    - servicenow.itsm
  
  tasks: 

  - name: Review a change request in ServiceNow
    servicenow.itsm.change_request:
      state: review
      number: "CHG0030045"
    delegate_to: localhost
  
  - name: Close a change request in ServiceNow
    servicenow.itsm.change_request:
      state: close
      number: "CHG0030045"
      close_code: "successful"
      close_notes: "{{ notes }}"
    delegate_to: localhost
    