---
- name: Create CR
  ansible.builtin.include_tasks: servicenow_create.yml
  when: servicenow_cr == "create"

- name: Implement CR
  ansible.builtin.include_tasks: servicenow_implement.yml
  when: servicenow_cr == "implement"

- name: Close CR
  ansible.builtin.include_tasks: servicenow_close.yml
  when: servicenow_cr == "close"

- name: Cancel CR
  ansible.builtin.include_tasks: servicenow_canceled.yml
  when: servicenow_cr == "canceled"

- name: Delete CR
  ansible.builtin.include_tasks: servicenow_deleted.yml
  when: servicenow_cr == "absent"