---
- name: Place a change request in ServiceNow in Review
  servicenow.itsm.change_request:
    state: review
    number: "{{ request.record.number }}"
  delegate_to: localhost

- name: Send e-mail to review
  community.general.mail:
    host: "{{ EMAIL_HOST }}"
    username: "{{ EMAIL_USERNAME }}"
    password: "{{ EMAIL_PASSWORD }}"
    port: "{{ EMAIL_PORT }}"
    subject: "Review completed ServiceNow Change Request {{ request.record.number }}"
    body: "You have a new CR review request. Please click on this URL to review: {{ lookup('env', 'SN_HOST') }}nav_to.do?uri=change_request.do?sysparm_query=number={{ request.record.number }}"
    from: tower@shadowman.dev
    to: "{{ to_email }}"
  delegate_to: localhost
